const state={scenes:[],media:[],project:'Untitled Project'};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function save(){localStorage.setItem('cinemorph-project',JSON.stringify(state))}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('cinemorph-project')||'{}'))}catch{} state.scenes=state.scenes||[];state.media=state.media||[]}
function renderScenes(){const box=$('#sceneList');$('#sceneCount').textContent=state.scenes.length;$('#totalDuration').textContent=state.scenes.reduce((a,s)=>a+s.duration,0)+'s';$('#assetCount').textContent=state.media.length;const pct=state.scenes.length?Math.min(100,state.scenes.length*20):0;$('#progressBar').style.width=pct+'%';$('#progressText').textContent=pct+'%';if(!state.scenes.length){box.innerHTML='<div class="empty">No scenes yet. Enter an idea above and generate a plan.</div>';renderTimeline();return}box.innerHTML=state.scenes.map((s,i)=>`<div class="scene"><div class="scene-num">${String(i+1).padStart(2,'0')}</div><div><h4>${escapeHtml(s.title)}</h4><p>${escapeHtml(s.description)}</p></div><span class="duration">${s.duration}s</span></div>`).join('');renderTimeline()}
function renderTimeline(){const box=$('#timelineTracks');if(!state.scenes.length){box.innerHTML='<div class="empty">Generate a scene plan to populate the timeline.</div>';return}box.innerHTML=['VIDEO','VOICEOVER','MUSIC'].map((label,idx)=>`<div class="track"><div class="track-label">${label}</div><div class="track-line">${state.scenes.map((s,i)=>`<div class="clip" style="flex:${s.duration}">${idx===0?'Scene '+(i+1):idx===1?'VO '+(i+1):'Music'}</div>`).join('')}</div></div>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function generate(){const idea=$('#ideaInput').value.trim();if(!idea){toast('Write an idea first');$('#ideaInput').focus();return}const total=Number($('#duration').value);const tone=$('#tone').value;const count=total<=30?3:total<=60?5:total<=90?6:8;const each=Math.max(4,Math.round(total/count));const titles=['Opening Hook','The Setup','Rising Action','The Discovery','The Turning Point','Final Reveal','Resolution','Call to Action'];state.scenes=Array.from({length:count},(_,i)=>({title:titles[i],description:`${tone} scene inspired by: ${idea}`,duration:i===count-1?total-each*(count-1):each}));state.project=idea.slice(0,45);save();renderScenes();toast('Scene plan generated');showView('studio')}
function writeScript(){const prompt=$('#scriptPrompt').value.trim()||$('#ideaInput').value.trim();if(!prompt){toast('Add a concept first');return}const tone=$('#tone').value;const dur=$('#duration').value;$('#scriptOutput').textContent=`TITLE: ${prompt.slice(0,55)}\n\n[OPENING — 0:00]\nStart with a strong visual hook that immediately creates curiosity.\n\n[SETUP — 0:08]\nIntroduce the world, the main subject, and the promise of the story.\n\n[RISING ACTION — 0:20]\nBuild momentum with ${tone.toLowerCase()} imagery and concise narration.\n\n[DISCOVERY — 0:35]\nReveal the key idea and give the audience a reason to keep watching.\n\n[FINALE — 0:50]\nBring the story to a memorable visual conclusion.\n\n[CALL TO ACTION — FINAL]\nEnd with a clear, natural next step for the audience.\n\nTarget runtime: ${dur} seconds.`;toast('Script created locally')}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#pageTitle').textContent=id==='script'?'Script Writer':id[0].toUpperCase()+id.slice(1)}
$$('.nav-item').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));
$('#generateBtn').addEventListener('click',generate);$('#scriptBtn').addEventListener('click',writeScript);
$('#addScene').addEventListener('click',()=>{state.scenes.push({title:'New Scene',description:'Describe what happens in this scene.',duration:5});save();renderScenes();toast('Scene added')});
$('#clearTimeline').addEventListener('click',()=>toast('Timeline is generated from your scenes'));
$('#newProject').addEventListener('click',()=>{if(confirm('Start a new project? Current local project will be cleared.')){state.scenes=[];state.media=[];state.project='Untitled Project';save();renderScenes();renderMedia();toast('New project created')}});
$('#exportBtn').addEventListener('click',()=>{const data=JSON.stringify({app:'CineMorph AI',version:1,project:state.project,scenes:state.scenes,media:state.media.map(m=>({name:m.name,type:m.type}))},null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='cinemorph-project.json';a.click();URL.revokeObjectURL(a.href);toast('Project exported')});
$('#mediaInput').addEventListener('change',e=>{[...e.target.files].forEach(file=>{const url=URL.createObjectURL(file);state.media.push({name:file.name,type:file.type,url});});save();renderMedia();toast(`${e.target.files.length} media added`)})
function renderMedia(){const box=$('#mediaGrid');$('#assetCount').textContent=state.media.length;if(!state.media.length){box.innerHTML='<div class="empty">No media added yet.</div>';return}box.innerHTML=state.media.map(m=>`<div class="media">${m.type.startsWith('image/')?`<img src="${m.url}" alt="">`:m.type.startsWith('video/')?`<video src="${m.url}" controls></video>`:`<div class="media-preview">♫ Audio</div>`}<div class="media-name" title="${escapeHtml(m.name)}">${escapeHtml(m.name)}</div></div>`).join('')}
load();renderScenes();renderMedia();
