package com.example.cinemorph

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Create
import androidx.compose.material.icons.filled.Folder
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Movie
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

private val Bg = Color(0xFF080B12)
private val Surface = Color(0xFF111827)
private val Purple = Color(0xFF8B5CF6)
private val Pink = Color(0xFFEC4899)

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { CineMorphApp() }
    }
}

@Composable
private fun CineMorphApp() {
    var tab by remember { mutableIntStateOf(0) }
    var prompt by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf(false) }
    val titles = listOf("Home", "Studio", "AI Script", "Library")

    MaterialTheme(colorScheme = darkColorScheme(primary = Purple, background = Bg, surface = Surface)) {
        Scaffold(
            containerColor = Bg,
            bottomBar = {
                NavigationBar(containerColor = Surface) {
                    listOf(Icons.Default.Home, Icons.Default.Movie, Icons.Default.AutoAwesome, Icons.Default.Folder).forEachIndexed { i, icon ->
                        NavigationBarItem(selected = tab == i, onClick = { tab = i }, icon = { Icon(icon, null) }, label = { Text(titles[i]) })
                    }
                }
            }
        ) { padding ->
            LazyColumn(modifier = Modifier.fillMaxSize().padding(padding).padding(horizontal = 20.dp), contentPadding = PaddingValues(vertical = 24.dp), verticalArrangement = Arrangement.spacedBy(18.dp)) {
                item {
                    Text("CineMorph AI", color = Color.White, fontSize = 30.sp, fontWeight = FontWeight.Bold)
                    Text("Next-gen AI text-to-video studio", color = Color(0xFF9CA3AF), fontSize = 14.sp)
                }
                item {
                    Card(shape = RoundedCornerShape(22.dp), colors = CardDefaults.cardColors(containerColor = Surface)) {
                        Column(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {
                            Text(if (tab == 2) "AI Scriptwriter" else "Create a cinematic video", color = Color.White, fontSize = 21.sp, fontWeight = FontWeight.SemiBold)
                            OutlinedTextField(value = prompt, onValueChange = { prompt = it }, modifier = Modifier.fillMaxWidth(), minLines = 4, placeholder = { Text("Describe your scene, character, action and cinematic lighting...") })
                            Button(onClick = { generated = true }, enabled = prompt.isNotBlank(), modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(14.dp)) {
                                Icon(Icons.Default.AutoAwesome, null); Spacer(Modifier.width(8.dp)); Text(if (tab == 2) "Generate Script" else "Generate Video")
                            }
                            if (generated) {
                                Text("Project created successfully", color = Color(0xFF86EFAC), fontWeight = FontWeight.Medium)
                                Text(prompt, color = Color.LightGray)
                            }
                        }
                    }
                }
                item { Text("Quick actions", color = Color.White, fontSize = 20.sp, fontWeight = FontWeight.Bold) }
                items(listOf("AI Scriptwriter", "Video Studio", "Timeline Editor", "Export & Share")) { action ->
                    Card(onClick = { tab = if (action == "AI Scriptwriter") 2 else 1 }, colors = CardDefaults.cardColors(containerColor = Surface), shape = RoundedCornerShape(16.dp)) {
                        Row(Modifier.fillMaxWidth().padding(18.dp), verticalAlignment = Alignment.CenterVertically) {
                            Icon(if (action == "AI Scriptwriter") Icons.Default.AutoAwesome else Icons.Default.Create, null, tint = Pink)
                            Spacer(Modifier.width(14.dp)); Text(action, color = Color.White, fontSize = 16.sp, fontWeight = FontWeight.Medium)
                        }
                    }
                }
            }
        }
    }
}
